create table bom_item (
    item_id          number generated by default as identity primary key,
    part_number      varchar2(50) not null unique,
    part_revision    varchar2(10) ,
    item_name        varchar2(200) not null,
    item_type        varchar2(30) check (item_type in ('ASSEMBLY', 'SUBASSEMBLY', 'COMPONENT')),
    
    -- Attributes
    item_size        varchar2(50),
    item_weight      varchar2(50),  -- e.g. kg
    item_length      varchar2(50),  -- e.g. cm
    warehouse        varchar2(100),
	supply_type      varchar2(50),
	lead_time		 varchar2(50),
    
    -- Commercial
    unit_of_measure  varchar2(30),
    standard_cost    number(12,2),
    supplier         varchar2(200)
);

create table bom_relation (
    relation_id        number generated by default as identity primary key,
    parent_item_id     number not null references bom_item(item_id),
    child_item_id      number not null references bom_item(item_id),
    quantity           number(12,3) default 1 not null,
    
    -- Relation-level attributes
    scrap_factor       number(5,2) default 0,   -- % scrap expected (e.g., 2.5%)
    yield_factor       number(5,2) default 100, -- % yield at this level (e.g., 98%)
    
    constraint uq_bom_relation unique (parent_item_id, child_item_id)
);

-- Assemblies
insert into bom_item (part_number, part_revision, item_name, item_type, warehouse) 
values ('LAPTOP-1000', 'A', 'Laptop Computer', 'ASSEMBLY', 'MAIN');

insert into bom_item (part_number, part_revision, item_name, item_type, warehouse) 
values ('MB-2000', 'A', 'Motherboard', 'SUBASSEMBLY', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, warehouse) 
values ('CHASSIS-3000', 'A', 'Chassis', 'SUBASSEMBLY', 'MECH');

insert into bom_item (part_number, part_revision, item_name, item_type, warehouse) 
values ('DISPLAY-4000', 'A', 'Display Assembly', 'SUBASSEMBLY', 'ELEC');

-- Components
insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('CPU-5000', 'A', 'Processor', 'COMPONENT', 'pcs', 250, 'Intel Corp', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('RAM-5100', 'A', 'Memory Module 8GB', 'COMPONENT', 'pcs', 40, 'Kingston', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('SSD-5200', 'A', 'Solid State Drive 512GB', 'COMPONENT', 'pcs', 80, 'Samsung', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('BAT-5300', 'A', 'Battery Pack', 'COMPONENT', 'pcs', 50, 'Panasonic', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('KB-5400', 'A', 'Keyboard', 'COMPONENT', 'pcs', 20, 'Logitech', 'MECH');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('CASE-5500', 'A', 'Plastic Case', 'COMPONENT', 'pcs', 30, 'Foxconn', 'MECH');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('LCD-5600', 'A', 'LCD Panel 15-inch', 'COMPONENT', 'pcs', 120, 'LG', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('CABLE-5700', 'A', 'Display Cable', 'COMPONENT', 'pcs', 5, 'Generic', 'ELEC');

insert into bom_item (part_number, part_revision, item_name, item_type, unit_of_measure, standard_cost, supplier, warehouse)
values ('SCREW-5800', 'A', 'Screw M2', 'COMPONENT', 'pcs', 0.05, 'Fastenal', 'MECH');



-- Laptop contains 1 motherboard, 1 chassis, 1 display, 1 battery
insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'LAPTOP-1000'
  and c.part_number = 'MB-2000';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'LAPTOP-1000'
  and c.part_number = 'CHASSIS-3000';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'LAPTOP-1000'
  and c.part_number = 'DISPLAY-4000';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'LAPTOP-1000'
  and c.part_number = 'BAT-5300';

-- Motherboard components
insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'MB-2000'
  and c.part_number = 'CPU-5000';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 2
from bom_item p, bom_item c
where p.part_number = 'MB-2000'
  and c.part_number = 'RAM-5100';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'MB-2000'
  and c.part_number = 'SSD-5200';

-- Chassis components
insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'CHASSIS-3000'
  and c.part_number = 'KB-5400';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'CHASSIS-3000'
  and c.part_number = 'CASE-5500';

-- Display assembly components
insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'DISPLAY-4000'
  and c.part_number = 'LCD-5600';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 1
from bom_item p, bom_item c
where p.part_number = 'DISPLAY-4000'
  and c.part_number = 'CABLE-5700';

-- Screws used in multiple assemblies
insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 20
from bom_item p, bom_item c
where p.part_number = 'CHASSIS-3000'
  and c.part_number = 'SCREW-5800';

insert into bom_relation (parent_item_id, child_item_id, quantity)
select p.item_id, c.item_id, 10
from bom_item p, bom_item c
where p.part_number = 'DISPLAY-4000'
  and c.part_number = 'SCREW-5800';

